### ISSUE TITLE
Leveraging Qiskit Runtime tutorial does not run

### ISSUE THREAD

**Issue by kt474** [Qiskit/qiskit-nature#1058]
### Environment

- **Qiskit Nature version**: 0.5.2
- **Python version**:  3.9
- **Operating system**:  Mac OS Ventura

### What is happening?

[07_leveraging_qiskit_runtime](https://github.com/Qiskit/qiskit-nature/blob/main/docs/tutorials/07_leveraging_qiskit_runtime.ipynb) tutorial does not run in quantum lab. I also could not get it to work in a local notebook 

![image](https://user-images.githubusercontent.com/20911417/218363204-3a169f09-7a33-432d-8a88-276cd763c32e.png)

### How can we reproduce the issue?

Run 07_leveraging_qiskit_runtime notebook 

### What should happen?

Notebook should run

**Comment by mrossinek** [comment]
By the look of that screenshot you are not using the latest version of the tutorial. You report that you are using Qiskit Nature version 0.5.2 for which you can find the correct version of the tutorial in one of these places:
- on the website [here](https://qiskit.org/documentation/nature/tutorials/07_leveraging_qiskit_runtime.html)
- on the `stable/0.5` branch on Github [here](https://github.com/Qiskit/qiskit-nature/blob/3ea8ac4ba05676236ab34a38307dc0162c3868e6/docs/tutorials/07_leveraging_qiskit_runtime.ipynb)

Updating your notebook will fix that issue for you.

<hr/>

As per the Quantum Lab: I do not know what version of Qiskit Nature they currently install, but I would hope that they provide the tutorials of the installed version correctly. If not, I suggest you open an issue with them.

**Comment by kt474** [comment]
@mrossinek a user reported an issue with this tutorial here https://github.com/Qiskit/qiskit-ibm-runtime/issues/690 and I am running into the same issue. Does the tutorial need to be updated or is this a bug on the runtime side? 

The Quantum Lab is using the stable/0.5 version of the tutorial

**Comment by mrossinek** [comment]
As I said before: I do not believe you are using the correct tutorial version. We fixed exactly this issue in version 0.5.2 so you have got to make sure to update that tutorial file.
Here is a screenshot of the correct tutorial which clearly differs from your screenshot in the description of this issue:
![screenshot_1677570367](https://user-images.githubusercontent.com/21973473/221787796-e21e2dc1-b1d9-4546-8fe1-b558b6703f78.png)
> Note how `num_electrons` is being set in the `ActiveSpaceTransformer`

References:
- original issue #990 
- PR which fixed it on `main` #995 
- PR which fixed it on `stable/0.5` #996 
- this got merged on Dec. 7th 2022 in 837812394c0569ad66b91ec6991d39b009f3c8b8
- the same day we released version 0.5.2: https://github.com/Qiskit/qiskit-nature/releases/tag/0.5.2

**Comment by kt474** [comment]
Apologies for not being clear - I was referencing a different issue that an external user brought up. Running this job always fails 
<img width="1094" alt="Screenshot 2023-02-28 at 1 34 54 PM" src="https://user-images.githubusercontent.com/20911417/221947391-2b0169d3-5d10-4b47-aab8-cd1d6376011d.png">

**Comment by mrossinek** [comment]
The error message shown is a bit sparse, not quite sure what is going on but I would suspect this to be related to the `VQEClient`-server side code. I was able to reproduce this both on stable and on main. Here is an example error message from the server side:

<details>

```
2023-03-01T07:43:56.566363610Z --- Logging error ---
2023-03-01T07:43:56.567343290Z Traceback (most recent call last):
2023-03-01T07:43:56.567394420Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 368, in _get_experiment
2023-03-01T07:43:56.567416307Z     exp = self.results[key]
2023-03-01T07:43:56.567521804Z IndexError: list index out of range
2023-03-01T07:43:56.567649830Z 
2023-03-01T07:43:56.567673334Z The above exception was the direct cause of the following exception:
2023-03-01T07:43:56.567690449Z 
2023-03-01T07:43:56.567709055Z Traceback (most recent call last):
2023-03-01T07:43:56.567726978Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute
2023-03-01T07:43:56.567751671Z     final_result = self.main(backend, self.messenger, **self.user_params)
2023-03-01T07:43:56.567770587Z   File "/code/./program.py", line 136, in main
2023-03-01T07:43:56.567788031Z     result = vqe.compute_minimum_eigenvalue(operator, aux_operators)
2023-03-01T07:43:56.567809134Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 546, in compute_minimum_eigenvalue
2023-03-01T07:43:56.567826970Z     opt_result = self.optimizer.minimize(
2023-03-01T07:43:56.567844812Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2023-03-01T07:43:56.567862045Z     get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)
2023-03-01T07:43:56.567880840Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2023-03-01T07:43:56.567899811Z     losses = _batch_evaluate(loss, points, max_evals_grouped)
2023-03-01T07:43:56.567917372Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 744, in _batch_evaluate
2023-03-01T07:43:56.567934515Z     results += _as_list(function(batch))
2023-03-01T07:43:56.567951739Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 620, in energy_evaluation
2023-03-01T07:43:56.567969577Z     sampled_expect_op = self._circuit_sampler.convert(expect_op, params=param_bindings)
2023-03-01T07:43:56.567986497Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/opflow/converters/circuit_sampler.py", line 214, in convert
2023-03-01T07:43:56.568003691Z     sampled_statefn_dicts = self.sample_circuits(circuit_sfns=circs, param_bindings=p_b)
2023-03-01T07:43:56.568021038Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/opflow/converters/circuit_sampler.py", line 351, in sample_circuits
2023-03-01T07:43:56.568079464Z     circ_results = results.data(circ_index)
2023-03-01T07:43:56.568098711Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 187, in data
2023-03-01T07:43:56.568117575Z     return self._get_experiment(experiment).data.to_dict()
2023-03-01T07:43:56.568135090Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 370, in _get_experiment
2023-03-01T07:43:56.568151082Z     raise QiskitError(f'Result for experiment "{key}" could not be found.') from ex
2023-03-01T07:43:56.568168021Z qiskit.exceptions.QiskitError: 'Result for experiment "50" could not be found.'
2023-03-01T07:43:56.568184906Z 
2023-03-01T07:43:56.568203340Z During handling of the above exception, another exception occurred:
2023-03-01T07:43:56.568219783Z 
2023-03-01T07:43:56.568236859Z Traceback (most recent call last):
2023-03-01T07:43:56.568253111Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit
2023-03-01T07:43:56.568270579Z     msg = self.format(record)
2023-03-01T07:43:56.568306913Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format
2023-03-01T07:43:56.568323483Z     return fmt.format(record)
2023-03-01T07:43:56.568341124Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format
2023-03-01T07:43:56.568358956Z     record.message = record.getMessage()
2023-03-01T07:43:56.568458450Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage
2023-03-01T07:43:56.568512753Z     msg = msg % self.args
2023-03-01T07:43:56.568532120Z TypeError: not all arguments converted during string formatting
2023-03-01T07:43:56.568548579Z Call stack:
2023-03-01T07:43:56.568646422Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap
2023-03-01T07:43:56.568663466Z     self._bootstrap_inner()
2023-03-01T07:43:56.568678338Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
2023-03-01T07:43:56.568693653Z     self.run()
2023-03-01T07:43:56.568710889Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-03-01T07:43:56.568727548Z     result = context.run(func, *args)
2023-03-01T07:43:56.568742388Z   File "/provider/server/main.py", line 75, in execute_program
2023-03-01T07:43:56.568758185Z     starter.execute()
2023-03-01T07:43:56.568774575Z   File "/provider/programruntime/program_starter_wrapper.py", line 98, in execute
2023-03-01T07:43:56.568789492Z     logger.error(
2023-03-01T07:43:56.568804083Z Message: 'Error executing program job cfvg4d4akfev56ped4c0'
2023-03-01T07:43:56.568817940Z Arguments: (QiskitError('Result for experiment "50" could not be found.'),)
2023-03-01T07:43:56.568866164Z webserver-starter - ERROR Failed to execute program: 'Result for experiment "50" could not be found.'
2023-03-01T07:43:56.568887140Z Traceback (most recent call last):
2023-03-01T07:43:56.568894428Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 368, in _get_experiment
2023-03-01T07:43:56.568902408Z     exp = self.results[key]
2023-03-01T07:43:56.568909220Z IndexError: list index out of range
2023-03-01T07:43:56.568914624Z 
2023-03-01T07:43:56.568921988Z The above exception was the direct cause of the following exception:
2023-03-01T07:43:56.568926877Z 
2023-03-01T07:43:56.568932342Z Traceback (most recent call last):
2023-03-01T07:43:56.568939358Z   File "/provider/server/main.py", line 75, in execute_program
2023-03-01T07:43:56.568945230Z     starter.execute()
2023-03-01T07:43:56.568950580Z   File "/provider/programruntime/program_starter_wrapper.py", line 102, in execute
2023-03-01T07:43:56.568956370Z     raise ex
2023-03-01T07:43:56.568961686Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute
2023-03-01T07:43:56.568966840Z     final_result = self.main(backend, self.messenger, **self.user_params)
2023-03-01T07:43:56.568972976Z   File "/code/./program.py", line 136, in main
2023-03-01T07:43:56.568978198Z     result = vqe.compute_minimum_eigenvalue(operator, aux_operators)
2023-03-01T07:43:56.568984479Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 546, in compute_minimum_eigenvalue
2023-03-01T07:43:56.569018945Z     opt_result = self.optimizer.minimize(
2023-03-01T07:43:56.569026345Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2023-03-01T07:43:56.569032050Z     get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)
2023-03-01T07:43:56.569038804Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2023-03-01T07:43:56.569055632Z     losses = _batch_evaluate(loss, points, max_evals_grouped)
2023-03-01T07:43:56.569062332Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/optimizers/spsa.py", line 744, in _batch_evaluate
2023-03-01T07:43:56.569068617Z     results += _as_list(function(batch))
2023-03-01T07:43:56.569075728Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 620, in energy_evaluation
2023-03-01T07:43:56.569081629Z     sampled_expect_op = self._circuit_sampler.convert(expect_op, params=param_bindings)
2023-03-01T07:43:56.569087368Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/opflow/converters/circuit_sampler.py", line 214, in convert
2023-03-01T07:43:56.569092798Z     sampled_statefn_dicts = self.sample_circuits(circuit_sfns=circs, param_bindings=p_b)
2023-03-01T07:43:56.569098633Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/opflow/converters/circuit_sampler.py", line 351, in sample_circuits
2023-03-01T07:43:56.569104062Z     circ_results = results.data(circ_index)
2023-03-01T07:43:56.569109585Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 187, in data
2023-03-01T07:43:56.569115422Z     return self._get_experiment(experiment).data.to_dict()
2023-03-01T07:43:56.569121065Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/result/result.py", line 370, in _get_experiment
2023-03-01T07:43:56.569126650Z     raise QiskitError(f'Result for experiment "{key}" could not be found.') from ex
2023-03-01T07:43:56.569132163Z qiskit.exceptions.QiskitError: 'Result for experiment "50" could not be found.'
```

</details>

Looks to me like some indexing error while trying to parse the results on the server side.

**Comment by Cryoris** [comment]
This error doesn't seem to happen if we turn off the `measurement_error_mitigation`, we'll check if there were any changes in the structure of the result. Until then setting `measurement_error_mitigation=False` could be a workaround for the users.

**Comment by mrossinek** [comment]
Closing this as per https://github.com/Qiskit/qiskit-nature/pull/1124.
