### ISSUE TITLE
Having problem to use Freeze core function

### ISSUE THREAD

**Issue by anhph** [Qiskit/qiskit-nature#163]
### Information

- **Qiskit Nature version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
when apply FreezeCoreTransformer to driver, and pass it to ElectronicStructureProblem, the problem second_q_ops doesn't work

### Steps to reproduce the problem
```
from qiskit_nature.drivers import PySCFDriver, UnitsType
from qiskit_nature.problems.second_quantization.electronic import ElectronicStructureProblem
from qiskit_nature.transformers import FreezeCoreTransformer
# Use PySCF, a classical computational chemistry software
# package, to compute the one-body and two-body integrals in
# electronic-orbital basis, necessary to form the Fermionic operator
driver = PySCFDriver(atom='O 0.0 0.0 0.0; H 0.757 0.586 0.0; H -0.757 0.586 0.0',
                     unit=UnitsType.ANGSTROM, charge=0, spin=0, basis='sto3g')

problem = ElectronicStructureProblem(FreezeCoreTransformer(driver))

second_q_ops = problem.second_q_ops()
```
gives
```
Traceback (most recent call last):
  File "<ipython-input-40-4d83576b02ea>", line 12, in <module>
    second_q_ops = problem.second_q_ops()
  File "/opt/conda/lib/python3.8/site-packages/qiskit_nature/problems/second_quantization/electronic/electronic_structure_problem.py", line 66, in second_q_ops
    self._molecule_data = cast(QMolecule, self.driver.run())
AttributeError: 'FreezeCoreTransformer' object has no attribute 'run'

Use %tb to get the full traceback.
```

**Comment by woodsp-ibm** [comment]
@anhph Did my suggestion solver your issue? If so please go ahead and close this.

**Comment by anhph** [comment]
Yes. Thanks a lot.
