### ISSUE TITLE
Problem with loading PySCFDriver on the IBM Quantum experience 

### ISSUE THREAD

**Issue by anhph** [Qiskit/qiskit-nature#258]
I got error when i tried to use the online IBM Quantum experience

from qiskit_nature.drivers import PySCFDriver

Traceback (most recent call last):
  File "<ipython-input-11-00edae455ff0>", line 2, in <module>
    from qiskit_nature.drivers import PySCFDriver
  File "/opt/conda/lib/python3.8/site-packages/qiskit_nature/drivers/__init__.py", line 155, in <module>
    from .pyscfd import PySCFDriver, InitialGuess
  File "/opt/conda/lib/python3.8/site-packages/qiskit_nature/drivers/pyscfd/__init__.py", line 26, in <module>
    from .pyscfdriver import PySCFDriver, InitialGuess
  File "/opt/conda/lib/python3.8/site-packages/qiskit_nature/drivers/pyscfd/pyscfdriver.py", line 23, in <module>
    from .integrals import compute_integrals
  File "/opt/conda/lib/python3.8/site-packages/qiskit_nature/drivers/pyscfd/integrals.py", line 27, in <module>
    from pyscf import gto, scf, ao2mo
  File "/opt/conda/lib/python3.8/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/opt/conda/lib/python3.8/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/opt/conda/lib/python3.8/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/opt/conda/lib/python3.8/site-packages/pyscf/lib/misc.py", line 47, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 179, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.

Use %tb to get the full traceback.

**Comment by woodsp-ibm** [comment]
Locally we have a workaround to pin h5py version to exclude the latest release until such time as PySCF is updated too - see #248 And FYI here is a ref to the issue in PySCF #pyscf/pyscf/issues/1003

**Comment by HuangJunye** [comment]
I faced the same problem. Solved it by installing h5py < 3.3

```
pip uninstall h5py
pip install -Iv h5py==3.2.1
```

**Comment by HuangJunye** [comment]
By the way, if you are using it on IBM Quantum platform / Jupyter notebook, you can use the following code in a cell to downgrade h5py. The `--yes` flag is necessary to confirm the uninstallation.

```
!pip uninstall h5py --yes
!pip install -Iv h5py==3.2.1
```

**Comment by mrossinek** [comment]
This issue appears to be fixed on the Quantum Lab since we have fixed the `h5py` dependence in Nature until PySCF produces a new release: https://github.com/Qiskit/qiskit-nature/commit/e714dfe87caf605f13fb83ec5289e596c94a18ca

**Comment by DevelopDaily** [comment]
@mrossinek  Just a friendly reminder. The PySCF has already produced the required release. But, I notice the default PySCF version on the Quantum Lab is still too old. Would you please upgrade it?

For now, I have to run this myself to get the things going.

!pip install --upgrade pyscf

**Comment by mrossinek** [comment]
Hi @DevelopDaily! I'm afraid that we are not the ones who are updating the packages on that server.

@woodsp-ibm @manoelmarques @stefan-woerner Do either of you know whom we need to contact in this regard?

**Comment by HuangJunye** [comment]
@mriedem is probably the person to contact for updating python packages in Jupyter image.

**Comment by mriedem** [comment]
The latest version of the user image in Quantum Lab now has unpinned pyscf (2.0.1).
