### ISSUE TITLE
Possible PYSCFDriver compatibility issues with Pyscf 2.0.1

### ISSUE THREAD

**Issue by JoelHBierman** [Qiskit/qiskit-nature#417]
### Information

- **Qiskit Nature version**: 0.2.2
- **Python version**: 3.9.6
- **Operating system**:  MacOS 11.4 (arm64)

### What is the current behavior?

running the code:

`from qiskit_nature.drivers import PYSCFDriver`

results in the following errors: (It seems there are several.)

```
/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/bin/python "/Users/joelbierman/Desktop/Misc./Old Code/Qiskit_Projects_Migration/Generate_H2_QMolecules.py"
/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/numint.py:31: UserWarning: XC functional libraries (libxc or XCfun) are not available.
  warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
Traceback (most recent call last):
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/misc.py", line 54, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxc_itrf.dylib, 6): Library not loaded: @rpath/libxc.9.dylib
  Referenced from: /Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxc_itrf.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/numint.py", line 25, in <module>
    from pyscf.dft import libxc
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/libxc.py", line 35, in <module>
    _itrf = lib.load_library('libxc_itrf')
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/misc.py", line 62, in load_library
    return numpy.ctypeslib.load_library(libname, libpath)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxc_itrf.dylib, 6): Library not loaded: @rpath/libxc.9.dylib
  Referenced from: /Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxc_itrf.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/misc.py", line 54, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxcfun_itrf.dylib, 6): Library not loaded: @rpath/libxcfun.2.dylib
  Referenced from: /Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxcfun_itrf.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joelbierman/Desktop/Misc./Old Code/Qiskit_Projects_Migration/Generate_H2_QMolecules.py", line 6, in <module>
    from qiskit_nature.drivers import PySCFDriver#, UnitsType, Molecule, HDF5Driver
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/qiskit_nature/drivers/__init__.py", line 53, in <module>
    from .pyscfd import PySCFDriver, InitialGuess
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/qiskit_nature/drivers/pyscfd/__init__.py", line 26, in <module>
    from .pyscfdriver import PySCFDriver, InitialGuess
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/qiskit_nature/drivers/pyscfd/pyscfdriver.py", line 23, in <module>
    from .integrals import compute_integrals
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/qiskit_nature/drivers/pyscfd/integrals.py", line 31, in <module>
    from pyscf.tools import dump_mat
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/tools/__init__.py", line 18, in <module>
    from pyscf.tools import cubegen
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/tools/cubegen.py", line 47, in <module>
    from pyscf.dft import numint
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/__init__.py", line 49, in <module>
    from pyscf.dft import numint
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/numint.py", line 28, in <module>
    from pyscf.dft import xcfun
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/dft/xcfun.py", line 32, in <module>
    _itrf = lib.load_library('libxcfun_itrf')
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/misc.py", line 62, in load_library
    return numpy.ctypeslib.load_library(libname, libpath)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxcfun_itrf.dylib, 6): Library not loaded: @rpath/libxcfun.2.dylib
  Referenced from: /Users/joelbierman/miniforge3/envs/Qiskit-0310-ARM64-pyscf17/lib/python3.9/site-packages/pyscf/lib/libxcfun_itrf.dylib
  Reason: image not found

```

### Steps to reproduce the problem

Install pyscf using the solution figured out at: https://github.com/pyscf/pyscf/issues/1096, install qiskit-nature, and try to import PYSCFDriver as shown above.

### What is the expected behavior?

No errors.

### Suggested solutions

I am posting this as a qiskit issue because this seems to be specific to how qiskit nature interacts with the pyscf installation via `PYSCFDriver` in some way. For instance, this does not seem to show up when just trying to import pyscf as: `from pyscf import *`, nor does it show up with the quantum computing chemistry package `pennylane-qchem`, which uses pyscf as a dependency. The most likely thing to me seems to be some kind of version incompatibility with the latest pyscf and where qiskit tries to look for the `libxcfun` and `libxc` libraries when importing `PYSCFDriver` . Pyscf by itself would not run properly if it could not find these libraries (and pyscf by itself seems to work properly), so it seems like qiskit is looking for it in the wrong place or thinks it isn't installed. 

EDIT: It appears that testing all imports with pure pyscf code with `from pyscf import *` is not the catch-all I thought it would be and that you need to try to import specific parts of pyscf to uncover additional errors. Because it's evident that this is more of a pyscf issue than a qiskit issue, I am closing this for now.

**Comment by woodsp-ibm** [comment]
Just as an FYI there is a PR #414 here which changes the setup.py to remove the version restriction that is in place when you do `pip install qiskit-nature[pyscf]` to install it as an optional extra. As you can see tests work fine under linux with 2.0.1 and mac is failing pending wheels for Mac being published.

**Comment by JoelHBierman** [comment]
Yes, the main issue seems to be that installing pyscf via pip does not automatically install the libicnt, libxc, and libxcfun libraries as it should. It also seems that building pyscf with the clang compiler does not work. It has to be changed to something else, but it is not clear to me whether this is specific to arm64 or if it also applies to x86.
