### ISSUE TITLE
continuous integration can't handle named jupyter kernels

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-nature#686]
### Environment

- **Qiskit Nature version**: N/A
- **Python version**: N/A
- **Operating system**: N/A

### What is happening?

Using a named jupyter kernel to run a notebook causes CI to fail.

### How can we reproduce the issue?

1. Create a named jupyter kernel, i.e.
```
python -m ipykernel install --user --name qiskit-nature
```
2. Edit one of the tutorial notebooks and run it with this kernel.
3. Submit a pull request with your changes.
4. Watch CI fail. Example: https://github.com/Qiskit/qiskit-nature/runs/6816145078?check_suite_focus=true

```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbsphinx.py", line 1043, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbsphinx.py", line 853, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 85, in preprocess
    with self.setup_kernel():
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbclient/client.py", line 599, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbclient/client.py", line 549, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbclient/util.py", line 97, in ensure_async
    result = await obj
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/manager.py", line 83, in wrapper
    raise e
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/manager.py", line 385, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/utils.py", line 38, in ensure_async
    return await obj
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/manager.py", line 348, in _async_pre_start_kernel
    self.kernel_spec,
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/manager.py", line 176, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 294, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named qiskit-nature
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 288, in build_update
    len(to_build))
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/share/miniconda/envs/psi4env/lib/python3.7/site-packages/nbsphinx.py", line 1054, in parse
    str(e))
nbsphinx.NotebookError: NoSuchKernel in tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb:
No such kernel named qiskit-nature
Notebook error:
NoSuchKernel in tutorials/11_quadratic_hamiltonian_and_slater_determinants.ipynb:
No such kernel named qiskit-nature
make: *** [Makefile:70: html] Error 2
```

### What should happen?

CI should handle it.

### Any suggestions?

The prototypes repositories seem to handle this fine. Maybe change the way we test notebooks to follow https://github.com/qiskit-community/quantum-prototype-template.

**Comment by manoelmarques** [comment]
How do the prototypes handle custom kernels ? I browsed that repo and all the tutorials I found use the python 3 kernel. Could you show an example in that repo ? 
I understand that for a custom kernel to work you need to install it with ipykernel.

Also, will people be able to run this tutorial in their local system ?
Why not just change to the standard kernel like all other tutorials ?
```
"metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
```

**Comment by kevinsung** [comment]
I created [qiskit-research](https://github.com/qiskit-research/qiskit-research) following the prototype template and the notebooks have named kernels, yet the CI handles it fine (for example, https://github.com/qiskit-research/qiskit-research/blob/main/docs/mzm_generation/data-collection.ipynb).

Prototypes uses [treon](https://github.com/ReviewNB/treon) to test notebooks. I guess this tool is somehow handling the kernel intelligently.

>Also, will people be able to run this tutorial in their local system ?

They should, I think Jupyter will just ask them to pick an existing kernel

>Why not just change to the standard kernel like all other tutorials ?

This is a hack because it requires the developer to manually change the kernel to a "fake" one before committing. If the system python is too old (see https://github.com/Qiskit/qiskit-nature/pull/680#discussion_r893613855) then the notebook file needs to be manually edited which is tedious and error-prone.

**Comment by kevinsung** [comment]
>I checked the prototypes repo. All the tutorials I found there use the python3 kernel. Could you point me to one that uses a custom kernel ?

You are correct. The example I have is from a different repository: https://github.com/qiskit-research/qiskit-research/blob/main/docs/mzm_generation/data-collection.ipynb

>What happens with people who may want to run this tutorial locally if this gets merged ? either they install the custom kernel or change it to use a standard one ?

They need to change it to whatever kernel they want to use. They would have to do this anyway.

>The system python is too old however it would be the one that the CI would be using to run the notebooks in order to build the docs, overriding any custom one. If it works in the CI why would not work locally and why people would not use it ?

We can't expect people to use a kernel that has the same name as the one the CI is using for their local development. For example, what if their system python differs from the CI python? What if they want to use a kernel from a virtual environment?

>I just don't think custom kernels should go into main.

This is reasonable. But manually editing jupyter notebook files is surely too tedious. Could we add a formatting script that automatically fixes the kernels in all the notebooks?

**Comment by manoelmarques** [comment]
> This is reasonable. But manually editing jupyter notebook files is surely too tedious. Could we add a formatting script that automatically fixes the kernels in all the notebooks?

What would the tool do ? Change it locally like the copyright tool and then override the custom kernel the notebook creator created ? So he/she would end up with python3 anyway, why not use it in the first place ?
A tool that changes on the fly just for CI purposes ? That is what nbsphinx_kernel_name would do. 
Tools are things that need to be created, tested etc. What is the cost/benefict ? People create one or two notebooks in PRs. They can easily change it locally before creating a PR. Currently absolutely all notebooks in all app repos and I believe qiskit-tutorials and Terra use the standard kernel, otherwise sphinx would fail for them on the first notebook found with a custom kernel.

**Comment by kevinsung** [comment]
>So he/she would end up with python3 anyway, why not use it in the first place ?

Again, we really can't expect people to use a kernel with the name "Python 3" for local development. This precludes people from using virtual environments.

>People create one or two notebooks in PRs. They can easily change it locally before creating a PR.

The issue is that they would have to change it every time they update the notebook. A PR could easily take multiple rounds of review, so this quickly becomes tedious. It seems like something that should be automated.

>What would the tool do ?

It goes through every tutorial notebook and changes the `kernelspec` part to be equal to
```
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
```
Perhaps `make format` could run this script after running black.

**Comment by woodsp-ibm** [comment]
We have so few notebooks submitted that spending time creating/testing/maintaining such a tool is pointless. The amount of tmie spent discussing this several notebooks could have been changed manually. Lets just make sure we check in Notebooks that CI can handle.

**Comment by mrossinek** [comment]
> What if they want to use a kernel from a virtual environment?

FWIW, this is not an argument. I heavily use virtual environments in all of my development and I have never had issues with the current behavior of CI.

That being said, you should be able to get your desired behavior if you use `--sys-prefix` for the ipykernel installation path instead of `--user`. This will install the kernel specification into the virtualenv location which you want to use. Then, you should _not_ use `--name` but instead only specify `--display-name` if need be. I would be willing to ignore changes to the `display_name` in the kernel spec as this has no effect on the notebook.
Here is a working command for reference:
```
# activate your virtualenv
python -m ipykernel install --sys-prefix --display-name "Qiskit Nature"
```
This will result in something like the following:
```
python -m jupyter kernelspec list
# Available kernels:
#  python3    /path/to/venv/share/jupyter/kernels/python3
```
So the `name` is indeed `python3` but it will be listed under a useful display name for you to find it under.

**Comment by kevinsung** [comment]
@mrossinek That doesn't work if I already have a kernel named `python3`. On my system `python3` refers to the system python and I would like to keep it that way.

**Comment by mrossinek** [comment]
Then you should open an issue with ipykernel because the virtualenv path should imo take precedence over the system path. (as is standard with e.g. resolving which python executable to use etc.)

But as I said, I do not have any issues with using virtual environments. I don't use the setup you're describing here but this seemed like the most logical fix

**Comment by kevinsung** [comment]
>Then you should open an issue with ipykernel because the virtualenv path should imo take precedence over the system path. (as is standard with e.g. resolving which python executable to use etc.)

If it did then I wouldn't be able to choose the system python for my kernel (which I may want to do sometimes).

To clarify, the setup I am describing uses a _single_ Jupyter server, with separate kernels for each virtual environment. This issue seems to show that Qiskit Nature's CI currently does not play well with this setup.
