### ISSUE TITLE
VQEClient failed unexpectedly

### ISSUE THREAD

**Issue by jvscursulim** [Qiskit/qiskit-nature#797]
### Environment

- **Qiskit Nature version**: 0.4.3
- **Python version**: 3.8.10
- **Operating system**:  Windows 11

### What is happening?

I was running some experiments, for a paper with some collaborators, using Qiskit Runtime through `VQEClient` and we were able to get our results without problems until some weeks ago, when for some unknown reason our jobs started to return the following error message: `ValueError: array split does not result in an equal division`. We have tested the Hamiltonian and our ansatz locally with `VQE` and everything is running without problems, even when we use `SPSA` and `QNSPSA` as optimizers. 

Logging error:
```
2022-08-18T19:05:53.650425133Z Traceback (most recent call last):
2022-08-18T19:05:53.650493331Z   File "/provider/programruntime/program_starter_wrapper.py", line 75, in execute
2022-08-18T19:05:53.650493331Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-08-18T19:05:53.650525304Z   File "/code/program.py", line 124, in main
2022-08-18T19:05:53.650525304Z     result = vqe.compute_minimum_eigenvalue(operator, aux_operators)
2022-08-18T19:05:53.650555861Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 530, in compute_minimum_eigenvalue
2022-08-18T19:05:53.650555861Z     opt_result = self.optimizer.minimize(
2022-08-18T19:05:53.650595371Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2022-08-18T19:05:53.650595371Z     get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)
2022-08-18T19:05:53.650624780Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2022-08-18T19:05:53.650624780Z     losses = _batch_evaluate(loss, points, max_evals_grouped)
2022-08-18T19:05:53.650655994Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 730, in _batch_evaluate
2022-08-18T19:05:53.650655994Z     batched_points = np.split(np.asarray(points), num_batches)
2022-08-18T19:05:53.650686371Z   File "<__array_function__ internals>", line 180, in split
2022-08-18T19:05:53.650716137Z   File "/opt/app-root/lib64/python3.8/site-packages/numpy/lib/shape_base.py", line 872, in split
2022-08-18T19:05:53.650716137Z     raise ValueError(
2022-08-18T19:05:53.650755928Z ValueError: array split does not result in an equal division
2022-08-18T19:05:53.650788365Z 
2022-08-18T19:05:53.650788365Z During handling of the above exception, another exception occurred:
2022-08-18T19:05:53.650788365Z 
2022-08-18T19:05:53.650819175Z Traceback (most recent call last):
2022-08-18T19:05:53.650862703Z   File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
2022-08-18T19:05:53.650862703Z     msg = self.format(record)
2022-08-18T19:05:53.650891817Z   File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
2022-08-18T19:05:53.650891817Z     return fmt.format(record)
2022-08-18T19:05:53.650921453Z   File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
2022-08-18T19:05:53.650921453Z     record.message = record.getMessage()
2022-08-18T19:05:53.650950555Z   File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
2022-08-18T19:05:53.650950555Z     msg = msg % self.args
2022-08-18T19:05:53.650983685Z TypeError: not all arguments converted during string formatting
2022-08-18T19:05:53.651016897Z Call stack:
2022-08-18T19:05:53.651195144Z   File "/code/program_starter.py", line 76, in <module>
2022-08-18T19:05:53.651195144Z     starter.execute()
2022-08-18T19:05:53.651226824Z   File "/provider/programruntime/program_starter_wrapper.py", line 79, in execute
2022-08-18T19:05:53.651226824Z     logger.error(f"Error executing program job {self.provider.execution_id}", ex)
2022-08-18T19:05:53.651269952Z Message: 'Error executing program job cbv8obolvap7pf94a5r0'
2022-08-18T19:05:53.651269952Z Arguments: (ValueError('array split does not result in an equal division'),)
2022-08-18T19:05:53.663503093Z 08/18/2022 07:05:53 PM - jaeger_tracing - INFO Span publisher exited
2022-08-18T19:05:53.663788700Z Traceback (most recent call last):
2022-08-18T19:05:53.663824397Z   File "/code/program_starter.py", line 76, in <module>
2022-08-18T19:05:53.663961193Z     2022-08-18T19:05:53.663988539Z starter.execute()2022-08-18T19:05:53.664015975Z 
2022-08-18T19:05:53.664043123Z   File "/provider/programruntime/program_starter_wrapper.py", line 81, in execute
2022-08-18T19:05:53.664132616Z     2022-08-18T19:05:53.664158450Z raise ex2022-08-18T19:05:53.664184725Z 
2022-08-18T19:05:53.664212623Z   File "/provider/programruntime/program_starter_wrapper.py", line 75, in execute
2022-08-18T19:05:53.664293040Z     2022-08-18T19:05:53.664320477Z final_result = self.main(backend, self.messenger, **self.user_params)2022-08-18T19:05:53.664346922Z 
2022-08-18T19:05:53.664373423Z   File "/code/program.py", line 124, in main
2022-08-18T19:05:53.664471301Z     2022-08-18T19:05:53.664498128Z result = vqe.compute_minimum_eigenvalue(operator, aux_operators)2022-08-18T19:05:53.664525149Z 
2022-08-18T19:05:53.664553177Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py", line 530, in compute_minimum_eigenvalue
2022-08-18T19:05:53.664744908Z     2022-08-18T19:05:53.664772872Z opt_result = self.optimizer.minimize(2022-08-18T19:05:53.664801158Z 
2022-08-18T19:05:53.664829319Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 512, in minimize
2022-08-18T19:05:53.665009489Z     2022-08-18T19:05:53.665036592Z get_eta, get_eps = self.calibrate(fun, x0, max_evals_grouped=self._max_evals_grouped)2022-08-18T19:05:53.665062100Z 
2022-08-18T19:05:53.665088903Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 333, in calibrate
2022-08-18T19:05:53.665232314Z     2022-08-18T19:05:53.665258189Z losses = _batch_evaluate(loss, points, max_evals_grouped)2022-08-18T19:05:53.665283323Z 
2022-08-18T19:05:53.665310691Z   File "/opt/app-root/lib64/python3.8/site-packages/qiskit/algorithms/optimizers/spsa.py", line 730, in _batch_evaluate
2022-08-18T19:05:53.665503760Z     2022-08-18T19:05:53.665529632Z batched_points = np.split(np.asarray(points), num_batches)2022-08-18T19:05:53.665556079Z 
2022-08-18T19:05:53.665593524Z   File "<__array_function__ internals>", line 180, in split
2022-08-18T19:05:53.665774985Z   File "/opt/app-root/lib64/python3.8/site-packages/numpy/lib/shape_base.py", line 872, in split
2022-08-18T19:05:53.665985043Z     2022-08-18T19:05:53.666011951Z raise ValueError(2022-08-18T19:05:53.666040560Z 
2022-08-18T19:05:53.666072938Z ValueError2022-08-18T19:05:53.666099500Z : 2022-08-18T19:05:53.666125054Z array split does not result in an equal division2022-08-18T19:05:53.666151052Z
```

### How can we reproduce the issue?

```python
from qiskit import IBMQ
from qiskit.algorithms.optimizers import SPSA
from qiskit.circuit.library import TwoLocal
from qiskit.opflow import I,X,Y,Z
from qiskit_nature.runtime import VQEClient

provider = IBMQ.load_account()
backend = provider.get_backend("ibmq_belem")

shots = 1024
maxiter = 100
num_qubits = 2

ansatz = TwoLocal(num_qubits, ["ry","rz"], entanglement="linear", reps=1)

optimizer = SPSA(maxiter=maxiter)
hamiltonian = (X ^ X) + (Y ^ Y) + (Z ^ Z)

vqe_client = VQEClient(ansatz=ansatz, optimizer=optimizer, provider=provider, backend=backend, shots=shots, measurement_error_mitigation=True)
vqe_client.compute_minimum_eigenvalue(hamiltonian)
```

### What should happen?

I think that it should return a `MinimumEigensolverResult` with the optimal value obtained in the experiment, if no other problem occurred during the computation problem.

**Comment by woodsp-ibm** [comment]
@Cryoris A change was made to the runtime max_evals_grouped I believe in regards of performance not so long back. Could this be related?

**Comment by Cryoris** [comment]
Note that this will only be fixed on the runtime once Terra released another stable version and the runtime images are updated accordingly
